apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-healing-app
  labels:
    app: self-healing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: self-healing
  template:
    metadata:
      labels:
        app: self-healing
    spec:
      containers:
      - name: network-tools
        image: nicolaka/netshoot
        command: ["sleep", "infinity"]
        livenessProbe:
          exec:
            command:
            - cat
            - /etc/hostname
          initialDelaySeconds: 5
          periodSeconds: 5
